disabled DFS channels
CreatorDev/uccp420wlan pull request #6
Opened 2016-11-29 14:16 UTC by tjobanpu

The DFS channels(48 onwards) are not supported in the AP mode, but we provide those channels to the network manager as supported, this displays the unsupported channels in the Luci GUI. 

Removing the unsupported channels from the Driver prevents those channels displaying in the Luci GUI thus preventing the user from selecting channel that we do not support.

Drawback: We support those channel in the STA mode but the STA will not work too in the DFS range , this is a temporary fix, the Luci needs to be configured as per our drivers capabilities, once that is done this change will be reverted.

2016-11-29 18:46 UTC, chaitu-tk commented on src/80211_if.c
> -	CHAN5G(5825, 38, 0), /* Channel 165 */
149-165 channels are not DFS, we can leave them enabled.

2016-11-30 10:16 UTC, chaitu-tk commented
I did some research on this, this is purely a bug in openwrt:iwinfo package, i have started a discussion with openwrt community, still awaiting their response, will udpate once i have some resolution on this.

https://lists.openwrt.org/pipermail/openwrt-devel/2016-November/042424.html

2016-11-30 13:04 UTC, tjobanpu commented on src/80211_if.c
> -	CHAN5G(5825, 38, 0), /* Channel 165 */
The channel 149-165 were not working as they are no-IR channels, I think this is because of the below mentioned bug in the iwinfo, I will put that back in.

2016-11-30 14:53 UTC, chaitu-tk commented on src/80211_if.c
> -	CHAN5G(5825, 38, 0), /* Channel 165 */
Yes, but once you configure country_code they should work fine.

2016-11-30 17:45 UTC, Ham22 requested changes
You have added changes from feedback as separate commit. Please instead rebase your history and squash them into a single commit.

Also add a reason why in the commit message so we know why we did this in a years time.

2016-12-01 14:25 UTC, Ham22 approved these changes

2016-12-01 15:55 UTC, chaitu-tk commented
Looks ok to me. Is this tested?

2016-12-01 16:05 UTC, tjobanpu commented
Yes .. but the noIR inclusions require the iwinfo bug to be fixed as, even if I set the country code to GB I am able to see the noIR channels, ideally that should not be displayed?

2016-12-01 17:07 UTC, chaitu-tk commented
Nope. Once you set country code NO_IR will be gone, so you are supposed to see those channels, they are no more restricted.

2016-12-02 08:59 UTC, merged